[versions]
agp = "8.7.3"
androidxJunit = "1.2.1"
appcompatVersion = "1.7.0"
cameraCore = "1.4.2"
markdown = "4.6.2"
coreKtx = "1.16.0"
espressoCoreVersion = "3.6.1"
firebaseBom = "33.13.0"
glide = "4.16.0"
googleServices = "4.4.2"
gradle = "8.6.1"
gson = "2.13.1"
hiltAndroid = "2.56.2"
hiltAndroidGradlePlugin = "2.50"
javaWebsocket = "1.6.0"
junit = "4.13.2"
lifecycleViewmodel = "2.8.7"
lottie = "6.6.6"
activity = "1.10.1"
constraintlayout = "2.2.1"
materialVersion = "1.12.0"
mockitoCore = "5.17.0"
navigationFragment = "2.8.9"
navigationSafeArgsGradlePlugin = "2.8.9"
okhttp = "4.12.0"
pagingRuntime = "3.3.6"
retrofit = "2.11.0"
roomRuntime = "2.7.1"
smartReply = "17.0.4"
swiperefreshlayout = "1.1.0"

[libraries]
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
markdown = { module = "io.noties.markwon:core", version.ref = "markdown" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleViewmodel" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
smart-reply = { module = "com.google.mlkit:smart-reply", version.ref = "smartReply" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

